In [1]:
import pandas as pd

data = {
    "customer_id": [101,102,103,104,105],
    "purchase_date": [
        "2024-01-05",
        "2024-02-10",
        "2024-03-15",
        "2024-03-20",
        "2024-04-02"
    ],
    "age": [25, 40, 35, 28, 50],
    "gender": ["Male", "Female", "Female", "Male", "Female"],
    "purchase_amount": [500, 1200, 750, 300, 2000],
    "is_subscribed": [1,0,1,0,1]
}

df = pd.DataFrame(data)

df["purchase_date"] = pd.to_datetime(df["purchase_date"])

print(df)

   customer_id purchase_date  age  gender  purchase_amount  is_subscribed
0          101    2024-01-05   25    Male              500              1
1          102    2024-02-10   40  Female             1200              0
2          103    2024-03-15   35  Female              750              1
3          104    2024-03-20   28    Male              300              0
4          105    2024-04-02   50  Female             2000              1

In [3]:
# Feature Extraction

# Extracting month, day, and year from purchase_date
df["purchase_month"] = df["purchase_date"].dt.month
df["purchase_day"] = df["purchase_date"].dt.day
df["purchase_year"] = df["purchase_date"].dt.year

# Creating age groups
def age_group(age):
    if age < 30:
        return "Young"
    elif age < 45:
        return "Middle"
    else:
        return "Senior"

# Applying the age_group function to create a new column
df["age_group"] = df["age"].apply(age_group)

# Encoding categorical variables
df["gender_encoded"] = df["gender"].map({
    "Male":0,
    "Female":1
})

# Creating a new feature for high value customers
df["high_value_customer"] = df["purchase_amount"].apply(
    lambda x: 1 if x > 1000 else 0
)

df

,customer_id,purchase_date,age,gender,purchase_amount,is_subscribed,purchase_month,purchase_day,purchase_year,age_group,gender_encoded,high_value_customer
0,101,2024-01-05,25,Male,500,1,1,5,2024,Young,0,0
1,102,2024-02-10,40,Female,1200,0,2,10,2024,Middle,1,1
2,103,2024-03-15,35,Female,750,1,3,15,2024,Middle,1,0
3,104,2024-03-20,28,Male,300,0,3,20,2024,Young,0,0
4,105,2024-04-02,50,Female,2000,1,4,2,2024,Senior,1,1

In [4]:
# Feture Scaling

# Min-Max Scaling

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_columns = ["age","purchase_amount","purchase_month"]

df[scaled_columns] = scaler.fit_transform(df[scaled_columns])

print(df)

   customer_id purchase_date   age  gender  purchase_amount  is_subscribed  \
0          101    2024-01-05  0.00    Male         0.117647              1
1          102    2024-02-10  0.60  Female         0.529412              0
2          103    2024-03-15  0.40  Female         0.264706              1
3          104    2024-03-20  0.12    Male         0.000000              0
4          105    2024-04-02  1.00  Female         1.000000              1

   purchase_month  purchase_day  purchase_year age_group  gender_encoded  \
0        0.000000             5           2024     Young               0
1        0.333333            10           2024    Middle               1
2        0.666667            15           2024    Middle               1
3        0.666667            20           2024     Young               0
4        1.000000             2           2024    Senior               1

   high_value_customer
0                    0
1                    1
2                    0
3                    0
4                    1

In [6]:
# standard Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["age_scaled","amount_scaled"]] = scaler.fit_transform(
    df[["age","purchase_amount"]]
)

df

,customer_id,purchase_date,age,gender,purchase_amount,is_subscribed,purchase_month,purchase_day,purchase_year,age_group,gender_encoded,high_value_customer,age_scaled,amount_scaled
0,101,2024-01-05,0.00,Male,0.117647,1,0.000000,5,2024,Young,0,0,-1.189286,-0.743827
1,102,2024-02-10,0.60,Female,0.529412,0,0.333333,10,2024,Middle,1,1,0.493666,0.413237
2,103,2024-03-15,0.40,Female,0.264706,1,0.666667,15,2024,Middle,1,0,-0.067318,-0.330590
3,104,2024-03-20,0.12,Male,0.000000,0,0.666667,20,2024,Young,0,0,-0.852696,-1.074417
4,105,2024-04-02,1.00,Female,1.000000,1,1.000000,2,2024,Senior,1,1,1.615634,1.735596